// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class AuthList extends Table {
  public static AuthList getRootAsAuthList(ByteBuffer _bb) { return getRootAsAuthList(_bb, new AuthList()); }
  public static AuthList getRootAsAuthList(ByteBuffer _bb, AuthList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public AuthList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String data() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer dataAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer dataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int errorcode() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createAuthList(FlatBufferBuilder builder,
      int dataOffset,
      int errorcode) {
    builder.startObject(2);
    AuthList.addErrorcode(builder, errorcode);
    AuthList.addData(builder, dataOffset);
    return AuthList.endAuthList(builder);
  }

  public static void startAuthList(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(0, dataOffset, 0); }
  public static void addErrorcode(FlatBufferBuilder builder, int errorcode) { builder.addInt(1, errorcode, 0); }
  public static int endAuthList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

