// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ControlAVTrans extends Table {
  public static ControlAVTrans getRootAsControlAVTrans(ByteBuffer _bb) { return getRootAsControlAVTrans(_bb, new ControlAVTrans()); }
  public static ControlAVTrans getRootAsControlAVTrans(ByteBuffer _bb, ControlAVTrans obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ControlAVTrans __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean audio() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public boolean video() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : true; }
  public boolean subtitle() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createControlAVTrans(FlatBufferBuilder builder,
      boolean audio,
      boolean video,
      boolean subtitle) {
    builder.startObject(3);
    ControlAVTrans.addSubtitle(builder, subtitle);
    ControlAVTrans.addVideo(builder, video);
    ControlAVTrans.addAudio(builder, audio);
    return ControlAVTrans.endControlAVTrans(builder);
  }

  public static void startControlAVTrans(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addAudio(FlatBufferBuilder builder, boolean audio) { builder.addBoolean(0, audio, true); }
  public static void addVideo(FlatBufferBuilder builder, boolean video) { builder.addBoolean(1, video, true); }
  public static void addSubtitle(FlatBufferBuilder builder, boolean subtitle) { builder.addBoolean(2, subtitle, false); }
  public static int endControlAVTrans(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

