// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ControlIFrame extends Table {
  public static ControlIFrame getRootAsControlIFrame(ByteBuffer _bb) { return getRootAsControlIFrame(_bb, new ControlIFrame()); }
  public static ControlIFrame getRootAsControlIFrame(ByteBuffer _bb, ControlIFrame obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ControlIFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte reserved() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createControlIFrame(FlatBufferBuilder builder,
      byte reserved) {
    builder.startObject(1);
    ControlIFrame.addReserved(builder, reserved);
    return ControlIFrame.endControlIFrame(builder);
  }

  public static void startControlIFrame(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addReserved(FlatBufferBuilder builder, byte reserved) { builder.addByte(0, reserved, 0); }
  public static int endControlIFrame(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

