// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ControlQueryAuthR extends Table {
  public static ControlQueryAuthR getRootAsControlQueryAuthR(ByteBuffer _bb) { return getRootAsControlQueryAuthR(_bb, new ControlQueryAuthR()); }
  public static ControlQueryAuthR getRootAsControlQueryAuthR(ByteBuffer _bb, ControlQueryAuthR obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ControlQueryAuthR __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean hasauthority() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createControlQueryAuthR(FlatBufferBuilder builder,
      boolean hasauthority) {
    builder.startObject(1);
    ControlQueryAuthR.addHasauthority(builder, hasauthority);
    return ControlQueryAuthR.endControlQueryAuthR(builder);
  }

  public static void startControlQueryAuthR(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addHasauthority(FlatBufferBuilder builder, boolean hasauthority) { builder.addBoolean(0, hasauthority, false); }
  public static int endControlQueryAuthR(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

