// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ControlMtu extends Table {
  public static ControlMtu getRootAsControlMtu(ByteBuffer _bb) { return getRootAsControlMtu(_bb, new ControlMtu()); }
  public static ControlMtu getRootAsControlMtu(ByteBuffer _bb, ControlMtu obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ControlMtu __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte seg(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int segLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer segAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer segInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createControlMtu(FlatBufferBuilder builder,
      int segOffset) {
    builder.startObject(1);
    ControlMtu.addSeg(builder, segOffset);
    return ControlMtu.endControlMtu(builder);
  }

  public static void startControlMtu(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSeg(FlatBufferBuilder builder, int segOffset) { builder.addOffset(0, segOffset, 0); }
  public static int createSegVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startSegVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endControlMtu(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

