// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ControlKillApp extends Table {
  public static ControlKillApp getRootAsControlKillApp(ByteBuffer _bb) { return getRootAsControlKillApp(_bb, new ControlKillApp()); }
  public static ControlKillApp getRootAsControlKillApp(ByteBuffer _bb, ControlKillApp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ControlKillApp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String app() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer appAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer appInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createControlKillApp(FlatBufferBuilder builder,
      int appOffset) {
    builder.startObject(1);
    ControlKillApp.addApp(builder, appOffset);
    return ControlKillApp.endControlKillApp(builder);
  }

  public static void startControlKillApp(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addApp(FlatBufferBuilder builder, int appOffset) { builder.addOffset(0, appOffset, 0); }
  public static int endControlKillApp(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

