// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ControlScreen extends Table {
  public static ControlScreen getRootAsControlScreen(ByteBuffer _bb) { return getRootAsControlScreen(_bb, new ControlScreen()); }
  public static ControlScreen getRootAsControlScreen(ByteBuffer _bb, ControlScreen obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ControlScreen __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float zoom() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createControlScreen(FlatBufferBuilder builder,
      float zoom) {
    builder.startObject(1);
    ControlScreen.addZoom(builder, zoom);
    return ControlScreen.endControlScreen(builder);
  }

  public static void startControlScreen(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addZoom(FlatBufferBuilder builder, float zoom) { builder.addFloat(0, zoom, 0.0f); }
  public static int endControlScreen(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

