// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ControlQueryAuth extends Table {
  public static ControlQueryAuth getRootAsControlQueryAuth(ByteBuffer _bb) { return getRootAsControlQueryAuth(_bb, new ControlQueryAuth()); }
  public static ControlQueryAuth getRootAsControlQueryAuth(ByteBuffer _bb, ControlQueryAuth obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ControlQueryAuth __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean queryauthority() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createControlQueryAuth(FlatBufferBuilder builder,
      boolean queryauthority) {
    builder.startObject(1);
    ControlQueryAuth.addQueryauthority(builder, queryauthority);
    return ControlQueryAuth.endControlQueryAuth(builder);
  }

  public static void startControlQueryAuth(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addQueryauthority(FlatBufferBuilder builder, boolean queryauthority) { builder.addBoolean(0, queryauthority, false); }
  public static int endControlQueryAuth(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

