// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InputString extends Table {
  public static InputString getRootAsInputString(ByteBuffer _bb) { return getRootAsInputString(_bb, new InputString()); }
  public static InputString getRootAsInputString(ByteBuffer _bb, InputString obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public InputString __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String str() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer strAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer strInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createInputString(FlatBufferBuilder builder,
      int strOffset) {
    builder.startObject(1);
    InputString.addStr(builder, strOffset);
    return InputString.endInputString(builder);
  }

  public static void startInputString(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addStr(FlatBufferBuilder builder, int strOffset) { builder.addOffset(0, strOffset, 0); }
  public static int endInputString(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

