// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InputTemperature extends Table {
  public static InputTemperature getRootAsInputTemperature(ByteBuffer _bb) { return getRootAsInputTemperature(_bb, new InputTemperature()); }
  public static InputTemperature getRootAsInputTemperature(ByteBuffer _bb, InputTemperature obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public InputTemperature __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float temperature() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createInputTemperature(FlatBufferBuilder builder,
      float temperature) {
    builder.startObject(1);
    InputTemperature.addTemperature(builder, temperature);
    return InputTemperature.endInputTemperature(builder);
  }

  public static void startInputTemperature(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addTemperature(FlatBufferBuilder builder, float temperature) { builder.addFloat(0, temperature, 0.0f); }
  public static int endInputTemperature(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

