// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InputProximity extends Table {
  public static InputProximity getRootAsInputProximity(ByteBuffer _bb) { return getRootAsInputProximity(_bb, new InputProximity()); }
  public static InputProximity getRootAsInputProximity(ByteBuffer _bb, InputProximity obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public InputProximity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean proximity() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createInputProximity(FlatBufferBuilder builder,
      boolean proximity) {
    builder.startObject(1);
    InputProximity.addProximity(builder, proximity);
    return InputProximity.endInputProximity(builder);
  }

  public static void startInputProximity(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addProximity(FlatBufferBuilder builder, boolean proximity) { builder.addBoolean(0, proximity, false); }
  public static int endInputProximity(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

