// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InputCursor extends Table {
  public static InputCursor getRootAsInputCursor(ByteBuffer _bb) { return getRootAsInputCursor(_bb, new InputCursor()); }
  public static InputCursor getRootAsInputCursor(ByteBuffer _bb, InputCursor obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public InputCursor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float x() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float y() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createInputCursor(FlatBufferBuilder builder,
      float x,
      float y) {
    builder.startObject(2);
    InputCursor.addY(builder, y);
    InputCursor.addX(builder, x);
    return InputCursor.endInputCursor(builder);
  }

  public static void startInputCursor(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addX(FlatBufferBuilder builder, float x) { builder.addFloat(0, x, 0.0f); }
  public static void addY(FlatBufferBuilder builder, float y) { builder.addFloat(1, y, 0.0f); }
  public static int endInputCursor(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

