// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InputKeyboard extends Table {
  public static InputKeyboard getRootAsInputKeyboard(ByteBuffer _bb) { return getRootAsInputKeyboard(_bb, new InputKeyboard()); }
  public static InputKeyboard getRootAsInputKeyboard(ByteBuffer _bb, InputKeyboard obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public InputKeyboard __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int key() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean pressed() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createInputKeyboard(FlatBufferBuilder builder,
      int key,
      boolean pressed) {
    builder.startObject(2);
    InputKeyboard.addPressed(builder, pressed);
    InputKeyboard.addKey(builder, key);
    return InputKeyboard.endInputKeyboard(builder);
  }

  public static void startInputKeyboard(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKey(FlatBufferBuilder builder, int key) { builder.addByte(0, (byte)key, (byte)0); }
  public static void addPressed(FlatBufferBuilder builder, boolean pressed) { builder.addBoolean(1, pressed, false); }
  public static int endInputKeyboard(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

