// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OutputString extends Table {
  public static OutputString getRootAsOutputString(ByteBuffer _bb) { return getRootAsOutputString(_bb, new OutputString()); }
  public static OutputString getRootAsOutputString(ByteBuffer _bb, OutputString obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public OutputString __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String msg() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer msgAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer msgInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createOutputString(FlatBufferBuilder builder,
      int msgOffset) {
    builder.startObject(1);
    OutputString.addMsg(builder, msgOffset);
    return OutputString.endOutputString(builder);
  }

  public static void startOutputString(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addMsg(FlatBufferBuilder builder, int msgOffset) { builder.addOffset(0, msgOffset, 0); }
  public static int endOutputString(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

