// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OutputScreen extends Table {
  public static OutputScreen getRootAsOutputScreen(ByteBuffer _bb) { return getRootAsOutputScreen(_bb, new OutputScreen()); }
  public static OutputScreen getRootAsOutputScreen(ByteBuffer _bb, OutputScreen obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public OutputScreen __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte rotation() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int width() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 1280; }
  public int height() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 720; }
  public int fps() { int o = __offset(10); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 60; }

  public static int createOutputScreen(FlatBufferBuilder builder,
      byte rotation,
      int width,
      int height,
      int fps) {
    builder.startObject(4);
    OutputScreen.addFps(builder, fps);
    OutputScreen.addHeight(builder, height);
    OutputScreen.addWidth(builder, width);
    OutputScreen.addRotation(builder, rotation);
    return OutputScreen.endOutputScreen(builder);
  }

  public static void startOutputScreen(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addRotation(FlatBufferBuilder builder, byte rotation) { builder.addByte(0, rotation, 0); }
  public static void addWidth(FlatBufferBuilder builder, int width) { builder.addShort(1, (short)width, (short)1280); }
  public static void addHeight(FlatBufferBuilder builder, int height) { builder.addShort(2, (short)height, (short)720); }
  public static void addFps(FlatBufferBuilder builder, int fps) { builder.addShort(3, (short)fps, (short)60); }
  public static int endOutputScreen(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

