// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResolutionLevel extends Table {
  public static ResolutionLevel getRootAsResolutionLevel(ByteBuffer _bb) { return getRootAsResolutionLevel(_bb, new ResolutionLevel()); }
  public static ResolutionLevel getRootAsResolutionLevel(ByteBuffer _bb, ResolutionLevel obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ResolutionLevel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int level() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 2; }
  public int width() { int o = __offset(6); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 480; }
  public int height() { int o = __offset(8); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 800; }

  public static int createResolutionLevel(FlatBufferBuilder builder,
      int level,
      int width,
      int height) {
    builder.startObject(3);
    ResolutionLevel.addLevel(builder, level);
    ResolutionLevel.addHeight(builder, height);
    ResolutionLevel.addWidth(builder, width);
    return ResolutionLevel.endResolutionLevel(builder);
  }

  public static void startResolutionLevel(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addLevel(FlatBufferBuilder builder, int level) { builder.addInt(0, level, 2); }
  public static void addWidth(FlatBufferBuilder builder, int width) { builder.addShort(1, (short)width, (short)480); }
  public static void addHeight(FlatBufferBuilder builder, int height) { builder.addShort(2, (short)height, (short)800); }
  public static int endResolutionLevel(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

