// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ShakeOnline extends Table {
  public static ShakeOnline getRootAsShakeOnline(ByteBuffer _bb) { return getRootAsShakeOnline(_bb, new ShakeOnline()); }
  public static ShakeOnline getRootAsShakeOnline(ByteBuffer _bb, ShakeOnline obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ShakeOnline __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String token() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer tokenInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String server() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer serverAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer serverInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String app() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer appAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer appInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public int type() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createShakeOnline(FlatBufferBuilder builder,
      int idOffset,
      int tokenOffset,
      int serverOffset,
      int appOffset,
      int type) {
    builder.startObject(5);
    ShakeOnline.addType(builder, type);
    ShakeOnline.addApp(builder, appOffset);
    ShakeOnline.addServer(builder, serverOffset);
    ShakeOnline.addToken(builder, tokenOffset);
    ShakeOnline.addId(builder, idOffset);
    return ShakeOnline.endShakeOnline(builder);
  }

  public static void startShakeOnline(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(1, tokenOffset, 0); }
  public static void addServer(FlatBufferBuilder builder, int serverOffset) { builder.addOffset(2, serverOffset, 0); }
  public static void addApp(FlatBufferBuilder builder, int appOffset) { builder.addOffset(3, appOffset, 0); }
  public static void addType(FlatBufferBuilder builder, int type) { builder.addInt(4, type, 0); }
  public static int endShakeOnline(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

