// automatically generated by the FlatBuffers compiler, do not modify

package CSProto;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TouchInfo extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TouchInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int x() { return bb.getInt(bb_pos + 0); }
  public int y() { return bb.getInt(bb_pos + 4); }
  public float force() { return bb.getFloat(bb_pos + 8); }

  public static int createTouchInfo(FlatBufferBuilder builder, int x, int y, float force) {
    builder.prep(4, 12);
    builder.putFloat(force);
    builder.putInt(y);
    builder.putInt(x);
    return builder.offset();
  }
}

